# Generated by Django 5.1.4 on 2024-12-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_user_alter_cliente_tipo'),
        ('prestamos', '0002_alter_prestamo_options_remove_prestamo_plazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
