# Generated by Django 5.1.4 on 2024-12-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
