# Generated by Django 5.1.3 on 2024-11-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_cuenta',
        ),
    ]
