# Generated by Django 5.1.3 on 2024-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
