# Generated by Django 5.1.4 on 2024-12-13 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_user_alter_cliente_tipo'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
