# Generated by Django 5.1.3 on 2024-11-15 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv_numero', models.CharField(max_length=4, unique=True)),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True)),
                ('tipo_tarjeta', models.CharField(max_length=50)),
                ('fecha_expiracion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'Tarjetas',
            },
        ),
    ]
